---
title: "Solutions - Introduction to visualising pharmacokinetic data using '<TT>R</TT>'"
output:
  bookdown::html_document2:
    fig_caption : TRUE
    number_sections: no

header-includes:
  - \usepackage{colortbl}
  - \usepackage{multirow}
  - \usepackage{float}
  - \floatplacement{figure}{H}
  - \floatplacement{table}{H}
  - \usepackage{booktabs}
  - \usepackage{caption}
  - \captionsetup{labelfont=bf,margin=12pt} 
  - \newcommand{\blandscape}{\begin{landscape}}
  - \newcommand{\elandscape}{\end{landscape}}
---

<style>
h1.title {
  font-size: 48px;

  text-align: center;
}
h4.author { 
  text-align: center;
}
body {
text-align: justify}
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.pos= "H")
library(tidyverse)
library(kableExtra)
```
**Tasks:** 

* Use a ggplot 'theme' to make your plot look more attractive 
* Can you make each line (ID) a different type? 
* Log transform the y-axis
* Plot data for *just* <TT>ID==A</TT>
* Plot each individual  

<br>

```{r ,eval=F}
ggplot(data=amox, aes(x=time, y=conc, group=ID))+ 
  geom_point()+
  xlab("Time (hours)")+
  ylab("Concentration of amoxicillin mg/L")+
  ggtitle("Amoxicillin PK data")+
  geom_line()+
  theme_bw()  # this is my favourite theme, what is yours?
``` 
```{r bwtheme,echo=F,fig.width=4.5,fig.height=2.5,fig.align = 'center', fig.cap="Plot using theme\\_bw()"}
ggplot(data=amox, aes(x=time, y=conc, group=ID))+ 
  geom_point()+
  xlab("Time (hours)")+
  ylab("Concentration of amoxicillin mg/L")+
  ggtitle("Amoxicillin PK data")+
  geom_line()+
  theme_bw(base_size=9)  # this is my favourite theme, what is yours?
``` 

```{r eval=F}
ggplot(data=amox, aes(time,conc, group=ID))+ 
  geom_point()+
  xlab("Time (hours)") + ylab("Concentration of amoxicillin (mg/L)")+
  geom_line()+
  scale_y_continuous(trans='log2') + #note that you have options log2 and log10 here
  theme_bw()
``` 

```{r logy,echo=F,fig.width=4.5,fig.height=2.5,fig.align = 'center', fig.cap="Semi-log plot"}
ggplot(data=amox, aes(time,conc, group=ID))+ 
  geom_point()+
  theme_bw(base_size=9)+
  xlab("Time (hours)") + ylab("Concentration of amoxicillin (mg/L)")+
  geom_line()+
  scale_y_continuous(trans='log2') + #note that you have options log2 and log10 here not loge
  theme_bw(base_size=9)
``` 

```{r,eval=F}
ggplot(data=amox, aes(time,conc, group=ID,linetype=ID))+ 
  geom_point()+
  xlab("Time (hours)") + ylab("Concentration of amoxicillin (mg/L)")+
  geom_line() +
  theme_bw() 
``` 
```{r difline, echo=F,fig.width=4.5,fig.height=2.5,fig.align = 'center', fig.cap="Plot with a different line type for each participant"}
ggplot(data=amox, aes(time,conc, group=ID,linetype=ID))+ 
  geom_point()+
  theme_bw(base_size=9)+
  xlab("Time (hours)") + ylab("Concentration of amoxicillin (mg/L)")+
  geom_line() +
  theme_bw(base_size=9) 
``` 

```{r eval=F}
ggplot(data=subset(amox,ID=='A'), aes(time,conc, group=ID))+ 
  geom_point()+
  ggtitle("Participant A data")+ #note I have put a title in here
  xlab("Time (hours)") + ylab("Concentration of amoxicillin (mg/L)")+
  geom_line()+
  theme_bw()
``` 
```{r subseta,echo=F,fig.width=4.5,fig.height=2.5,fig.align = 'center', fig.cap="Plot of data for participant 'A'"}
ggplot(data=subset(amox,ID=='A'), aes(time,conc, group=ID))+ 
  geom_point()+
  ggtitle("Participant A data")+ #note I have put a title in here
  xlab("Time (hours)") + ylab("Concentration of amoxicillin (mg/L)")+
  geom_line()+
  theme_bw(base_size=9)
``` 

```{r ,eval=F}
ggplot(data=subset(amox), aes(time,conc, group=ID))+ 
  geom_point()+
  xlab("Time (hours)") + ylab("Concentration of amoxicillin (mg/L)")+
  geom_line()+ 
  facet_wrap(vars(ID))+
  theme_bw()
```
```{r facet,echo=F,fig.width=7,fig.height=5,fig.align = 'center', fig.cap="Plot using facet_wrap() to give panel per ID"}
ggplot(data=subset(amox), aes(time,conc, group=ID))+ 
  geom_point()+
  xlab("Time (hours)") + ylab("Concentration of amoxicillin (mg/L)")+
  geom_line()+ 
  facet_wrap(vars(ID))+
  theme_bw(base_size=9)
``` 